services:
  postgres:
    image: postgres:16
    container_name: psygateway_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: psygateway_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4:8.8
    container_name: psygateway_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@psygateway.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  consul:
    image: hashicorp/consul:1.15
    container_name: consul
    restart: always
    ports:
      - "8500:8500"     # Web UI / API
      - "8600:8600/udp" # DNS interface
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: ["consul", "agent", "-server", "-bootstrap", "-ui", "-client=0.0.0.0", "-data-dir=/consul/data"]
    volumes:
      - consul_data:/consul/data

  user-service:
    build:
      context: .
      dockerfile: Dockerfile.userservice
    container_name: user-service
    restart: always
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - USER_SERVICE_PORT=3001
      - CONSUL_ADDRESS=consul:8500
    depends_on:
      - postgres
      - consul
    networks:
      - default

  product-service:
    build:
      context: .
      dockerfile: Dockerfile.productservice
    container_name: product-service
    restart: always
    ports:
      - "3002:3002"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - PRODUCT_SERVICE_PORT=3002
      - CONSUL_ADDRESS=consul:8500
    depends_on:
      - postgres
      - consul
    networks:
      - default

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: psygateway
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - GATEWAY_PORT=8000
      - CONSUL_ADDRESS=consul:8500
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - consul
      - redis
      - user-service
      - product-service
    networks:
      - default

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
  consul_data:
